# Generated by Django 4.2.7 on 2025-03-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('W', 'Work'), ('P', 'Personal'), ('H', 'Home')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('IP', 'In Progress'), ('C', 'Completed')], default='P', max_length=2),
        ),
    ]
