# Generated by Django 4.2.7 on 2025-03-21 02:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_category_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='static/images/nobody.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
